name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Update codecov
        uses: codecov/codecov-action@v5

      - name: Pack NuGet packages (CI versions)
        if: ${{ startsWith(github.ref, 'refs/heads/') && github.event_name == 'push' }}
        run: dotnet pack --configuration Release --output nupkgs --version-suffix "ci.$(date -u +%Y%m%dT%H%M%S)+sha.${GITHUB_SHA:0:9}" -p:ContinuousIntegrationBuild=true

      - name: Pack NuGet packages (Release versions)
        if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' }}
        run: dotnet pack --configuration Release --output nupkgs -p:ContinuousIntegrationBuild=true

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: EFCore.InMemory.NodaTime
          path: nupkgs

      - name: Publish to GitHub Packages
        if: ${{ github.event_name == 'push' }}
        run: |
          dotnet nuget add source --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push "nupkgs/*.nupkg" --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate
